BasicEstructure_JSF/src/java/Controlador/NbaPlayerManagedBean.java
package Controlador;

import Entidades.NbaPlayer;
import Modelos.NbaPlayerModel;
import java.io.Serializable;
import java.util.List;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;

@Named(value = "BNbaPlayer")
@SessionScoped
public class NbaPlayerManagedBean implements Serializable {

    private NbaPlayer nbap = new NbaPlayer();
    private NbaPlayerModel nbaplayermodel = new NbaPlayerModel();

    public NbaPlayerManagedBean() {
    }

    /**
     * @return the nbap
     */
    public NbaPlayer getNbaPlayer(){
        return nbap;
    }
    
    /**
     * @param nbap the nba to set
     */
    public void setNbaPlayer(NbaPlayer nbap){
        this.nbap = nbap;
    }
    
    /**
     * @return the nbaplayermodel
     */
    public NbaPlayer getShowMVP() {
        return nbaplayermodel.showMVP();
    }

    public String getAgregarPlayer() {
        nbaplayermodel.registrar(this.nbap);
        this.nbap = new NbaPlayer();
        
        return "index?faces-redirect=true";
    }

    public String getEditarPlayer() {
        nbaplayermodel.editar(this.nbap);
        this.nbap = new NbaPlayer();
        
        return "index?faces-redirect=true";
    }

    public String getEliminarPlayer() {
        nbaplayermodel.eliminar(this.nbap);
        this.nbap = new NbaPlayer();
        
        return "index?faces-redirect=true";
    }
    
    public List<NbaPlayer> getListaNbaPlayer() {
        return nbaplayermodel.listaPlayers();
    }
}

BasicEstructure_JSF/web/formData.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Actividad Semana 3 - P4</title>
        <link href="Recursos/css/Estilo.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
	<div class="content">
            <div class="container">
                <div class="example">
                    <h1>Datos del MVP</h1>
                    <h:form>
                        <label>ID:</label>
                        <h:inputText class="txt" value="#{BNbaPlayer.showMVP.id}"/>
                        <label>NOMBRE:</label>
                        <h:inputText class="txt" value="#{BNbaPlayer.showMVP.nombre}"/>
                        <label>NUMERO DE CAMISETA:</label>
                        <h:inputText class="txt" value="#{BNbaPlayer.showMVP.numero}"/>
                        <label>FRANQUICIA:</label>
                        <h:inputText class="txt" value="#{BNbaPlayer.showMVP.equipo}"/>
                        <h:commandLink class="btn" value="REGRESAR" action="index"/>
                    </h:form>
                </div>
            </div>
	</div>
    </h:body>
</html>

BasicEstructure_JSF/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Actividad Semana 3 - P4</title>
        <link href="Recursos/css/Estilo.css" rel="stylesheet" type="text/css"/>
    </h:head>
    <h:body>
        <div class="content">
            <div class="container">
                <div class="example">
                    <div class="title">
                        <img src="Recursos/img/premio.png" alt=""/>
                        <h1>MVP: #{BNbaPlayer.showMVP.nombre}</h1>
                    </div>
                    <p>
                        ¡El MVP del partido es otorgado a #{BNbaPlayer.showMVP.nombre}, 
                        jugador con el dorsal numero #{BNbaPlayer.showMVP.numero} 
                        correspondiente al equipo puntero de la liga: #{BNbaPlayer.showMVP.equipo}!
                    </p>
                    <h:form>
                        <h:commandLink class="fdFloatBtn" value="Ver Datos en Form" action="formData" />
                    </h:form>
                </div>
                <div class="containerContent">
                    <div class="lista">
                        <table>
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>NAME</th>
                                    <th>NUMBER</th>
                                    <th>TEAM</th>
                                </tr>
                            </thead>
                            <tbody>
                                <c:forEach items="#{BNbaPlayer.listaNbaPlayer}" var="lista">
                                    <tr>
                                        <td>#{lista.id}</td>
                                        <td>#{lista.nombre}</td>
                                        <td>#{lista.numero}</td>
                                        <td>#{lista.equipo}</td>
                                    </tr>
                                </c:forEach>
                            </tbody>
                        </table>
                    </div>
                    <div class="crud">
                        <h:form class="crudOption add">
                            <div class="opcs">
                                <div class="control">
                                    <label>ID: </label>
                                    <h:inputText value="#{BNbaPlayer.nbaPlayer.id}"/>
                                    <label>NUMERO: </label>
                                    <h:inputText value="#{BNbaPlayer.nbaPlayer.numero}"/>
                                </div>
                                <div class="control">
                                    <label>NOMBRE: </label>
                                    <h:inputText value="#{BNbaPlayer.nbaPlayer.nombre}"/>
                                    <label>EQUIPO: </label>
                                    <h:inputText value="#{BNbaPlayer.nbaPlayer.equipo}"/>
                                </div>
                            </div>
                            <div class="opc">
                                <h:commandButton class="btn" value="GUARDAR" 
                                                 action="#{BNbaPlayer.getAgregarPlayer()}"/>
                            </div>
                        </h:form>
                        <h:form class="crudOption edit">
                            <div class="opcs">
                                <div class="control">
                                    <label>ID: </label>
                                    <h:inputText value="#{BNbaPlayer.nbaPlayer.id}"/>
                                    <label>NUMERO: </label>
                                    <h:inputText value="#{BNbaPlayer.nbaPlayer.numero}"/>
                                </div>
                                <div class="control">
                                    <label>NOMBRE: </label>
                                    <h:inputText value="#{BNbaPlayer.nbaPlayer.nombre}"/>
                                    <label>EQUIPO: </label>
                                    <h:inputText value="#{BNbaPlayer.nbaPlayer.equipo}"/>
                                </div>
                            </div>
                            <div class="opc">
                                <h:commandButton class="btn" value="EDITAR" 
                                                 action="#{BNbaPlayer.getEditarPlayer()}"/>
                            </div>
                        </h:form>
                        <h:form class="crudOption del">
                            <div class="opcs">
                                <div class="control">
                                    <label>ID: </label>
                                    <h:inputText value="#{BNbaPlayer.nbaPlayer.id}"/>
                                </div>
                            </div>
                            <div class="opc">
                                <h:commandButton class="btn" value="ELIMINAR" 
                                                 action="#{BNbaPlayer.getEliminarPlayer()}"/>
                            </div>
                        </h:form>
                    </div>
                </div>
            </div>
        </div>
    </h:body>
</html>